export const AiClassifiedList = [
	{
		id: '1',
		title: '2D 게임',
		hashtag: '미분류됨 1 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '2',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '3',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '4',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '5',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '6',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '7',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '8',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '9',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '10',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '게임',
	},
	{
		id: '11',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '리액트',
	},
	{
		id: '12',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '리액트',
	},
	{
		id: '13',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '리액트',
	},
	{
		id: '14',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '리액트',
	},
	{
		id: '15',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '리액트',
	},
	{
		id: '16',
		title: '2D 게임',
		hashtag: '미분류됨 2 셀피 메니저 만들기',
		url: 'https://udangtangtang-cording-oldcastle.tistory.com',
		date: '9월 10일',
		category: '미분류',
		folder: '리액트2',
	},
];
